# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-mwaa
  description: "This component provisions Amazon managed workflows for Apache Airflow"
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








